### ISSUE TITLE
where can i find train and test data

### ISSUE THREAD

**Issue by ChenKevin0123** [srendle/libfm#15]
i can only find rating.dat,movies.dat and ratings.dat or movies.csv,rating.csv on MovieLens .
Where can i find train and test data?

**Comment by breuderink** [comment]
Many datasets in the LibSVM format can be found here: https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/. I believe that libFM can read those, and they are already split into a training and test set.

For recent MovieLens data you have to split the data yourself. See section named "Cross Validation" in http://files.grouplens.org/datasets/movielens/ml-latest-small-README.html.

**Comment by ChenKevin0123** [comment]
thank you very much.
