### ISSUE TITLE
Error while using als method

### ISSUE THREAD

**Issue by ajitbarik1992** [srendle/libfm#24]
If method is given **als**, code changes the `param_method` value to **mcmc** as als is an mcmc without sampling and hyperparameter inference (File : libfm.cpp, Line : 123).

While saving the model it checks for the model to be either 'sgd' or 'als', but as the param_method has been changed to 'mcmc' , it won't save model file.

**Comment by sjtuxiaoming** [comment]
I met the same problems. I use 'als' the training is ok but can't save the model.  As below:
Writing FM model...
WARNING: load/save enabled only for SGD and ALS. Nothing will be saved.

but if I shift to 'sgd' with -learn_rate 0.1 .The model saved is ok but the training &testing are all 0.
