### ISSUE TITLE
terminal bash isn't known

### ISSUE THREAD

**Issue by doczkal** [srendle/libfm#25]
I am using calibre (calibre 3.3) and started it in a shell.
Once in a while I receive the following error:

** (pcmanfm:26810): WARNING **: terminal bash isn't known, consider report it to LibFM developers
/usr/bin/xdg-open: line 709: : command not found

This is the ls output so the file is there ...
% ls -l /usr/bin/xdg-open 
-rwxr-xr-x 1 root root 22746 Jan 20  2017 /usr/bin/xdg-open

and bash is installed:
% which bash
/bin/bash
% ls -l /bin/bash 
-rwxr-xr-x 1 root root 725872 Dec  8  2016 /bin/bash

But the default shell is not bash but csh:
% echo $SHELL
/bin/csh

Is there anything else you need to know?

**Comment by thierry-silbermann** [comment]
Go to the right project: https://github.com/lxde/libfm 
:-)

**Comment by doczkal** [comment]
Sorry, I missed your initial reply. Does this mean it's solved now?
