### ISSUE TITLE
Assertion error in Transpose

### ISSUE THREAD

**Issue by binga** [srendle/libfm#5]
Hi,

I have prepared a Train.x and Train.y file after which I am trying to transpose the input matrix to obtain Train.xt and during this transpose operation, I am encountering the following error!

Assertion failed: out_cache_col_num > 0, file tools\transpose.cpp, line 125

Any idea what this error is?
Could you suggest what can be done?

Thanks,
Phani

**Comment by srendle** [comment]
One more note:
I would recommend not to specify the flag "cache_size" at all when running the libFM executable. libFM chooses automatically the right amount of memory when "cache_size" is not specified.

The flag "cache_size" in the libFM executable is only useful, if your data does not fit into memory. But then the speed is bounded by disk I/O and learning will be slow.
